services:
  optimizer_api_web:
    build:
      context: .
      args:
        DJANGO_SECRET_KEY: ${DJANGO_SECRET_KEY}
    container_name: optimizer_api_web
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - optimizer_api_redis
    networks:
      - shared_network
  optimizer_api_celery:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: optimizer_api_celery
    command: celery -A optimizer_api worker --loglevel=info
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - optimizer_api_web
      - optimizer_api_redis  
    networks:
      - shared_network

  optimizer_api_redis:
    image: redis:7
    container_name: optimizer_api_redis
    networks:
      - shared_network
  
networks:
  shared_network:
    external: true
