version: '3.9'

services:
  optimizer_web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: optimizer_api_web
    command: gunicorn optimizer_api.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/app
    ports: []  # 🔒 Don't expose to host. Access only via Docker network.
    env_file:
      - .env
    depends_on:
      - optimizer_redis
    networks:
      - optimizernet
      - optimizer_bridge  # ✅ allow mvp access

  optimizer_celery:
    build:
      context: .
      dockerfile: celery_worker.Dockerfile
    container_name: optimizer_api_celery
    command: celery -A optimizer_api worker --loglevel=info
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - optimizer_redis
    networks:
      - optimizernet

  optimizer_redis:
    image: redis:7-alpine
    container_name: optimizer_api_redis
    volumes:
      - optimizer_redis_data:/data
    networks:
      - optimizernet

volumes:
  optimizer_redis_data:

networks:
  optimizernet:
  optimizer_bridge:
    external: true
